### ISSUE TITLE
Reddit OAuth2

### ISSUE THREAD

**Issue by mhdatie** [jacobtabak/droidcon#2]
Hey, thanks a lot for the Deserializer, that was smart. It would be nice if you provided an example or tutorial on how to authenticate to Reddit using Retrofit, all in one class.

So depending on the request or URL passed, you can extend the builder. 

Thanks

**Comment by jacobtabak** [comment]
I have no plans to add any new features to this but thanks for the feedback! Feel free to submit a pull request if you decide you want to implement it.
